---
config:
  flowchart:
    curve: linear
---
graph TD;
    __start__([<p>__start__</p>]):::first
    router(router)
    brainstorm_node(brainstorm_node)
    specification_node(specification_node)
    lesson_plan_node(lesson_plan_node)
    debate_outline_node(debate_outline_node)
    political_leteracy_node(political_leteracy_node)
    generic_activity_node(generic_activity_node)
    tools(tools)
    __end__([<p>__end__</p>]):::last
    __start__ --> router;
    router -.-> brainstorm_node;
    router -.-> specification_node;
    router -.-> lesson_plan_node;
    router -.-> debate_outline_node;
    router -.-> political_leteracy_node;
    router -.-> generic_activity_node;
    brainstorm_node -.-> tools;
    brainstorm_node -. end .-> __end__;
    specification_node -.-> tools;
    specification_node -. end .-> __end__;
    lesson_plan_node -.-> tools;
    lesson_plan_node -. end .-> __end__;
    debate_outline_node -.-> tools;
    debate_outline_node -. end .-> __end__;
    political_leteracy_node -.-> tools;
    political_leteracy_node -. end .-> __end__;
    generic_activity_node -.-> tools;
    generic_activity_node -. end .-> __end__;
    tools -.-> brainstorm_node;
    tools -.-> specification_node;
    tools -.-> lesson_plan_node;
    tools -.-> debate_outline_node;
    tools -.-> political_leteracy_node;
    tools -.-> generic_activity_node;
    classDef default fill:#f2f0ff,line-height:1.2;
    classDef first fill-opacity:0;
    classDef last fill:#bfb6fc;

